[processes]
web = "uvicorn main:app --host 0.0.0.0 --port 8080"

app = "news-analytics"
primary_region = "iad"  # US East (Virginia)

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
  DATA_DIR = "/app/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[mounts]
  source = "news_analytics_data"
  destination = "/app/data"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
