app = "news-analytics-api"
primary_region = "iad"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[env]
  PORT = "8080"
  PYTHONUNBUFFERED = "1"
  DATA_DIR = "/app/data"
